/*
Copyright 2025 Richard Kosegi

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package openapi

import (
	"net/http"

	"github.com/rkosegi/go-http-commons/output"
)

var out = output.DefaultOutput()

// SpecFileProvider is function similar to PathToRawSpec generated by oapi-codegen
// see https://github.com/oapi-codegen/oapi-codegen/blob/bdc4edce7476be0791dc670d695fd78378e0e9b6/pkg/codegen/templates/inline.tmpl#L38
type SpecFileProvider func(pathToFile string) map[string]func() ([]byte, error)

// SpecHandler is http handler that serves openapi spec embedded into application.
// common use of this handler is something like:
//
//	r := mux.NewRouter()
//	r.HandleFunc("/spec/opeanapi.v1.json", openapi.SpecHandler(api.PathToRawSpec))
func SpecHandler(prov SpecFileProvider) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		if data, err := prov(r.URL.Path)[r.URL.Path](); err != nil {
			out.SendWithStatus(w, err, http.StatusInternalServerError)
			return
		} else {
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write(data)
		}
	}
}
