// Package config provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package config

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// TLSConfig TLS configuration
type TLSConfig struct {
	// CertFile Path to file with certificate bundle
	CertFile string `json:"cert_file" yaml:"cert_file"`

	// KeyFile Path to file with private key
	KeyFile string `json:"key_file" yaml:"key_file"`
}

// CorsConfig CORS configuration
type CorsConfig struct {
	// AllowedOrigins AllowedOrigins controls value of Access-Control-Allow-Origin header.
	AllowedOrigins []string `json:"allowed_origins" yaml:"allowed_origins"`

	// MaxAge MaxAge controls value of Access-Control-Max-Age header.
	MaxAge int `json:"max_age" yaml:"max_age"`
}

// ServerConfig Server configuration
type ServerConfig struct {
	// APIPrefix API prefix
	APIPrefix string `json:"api_prefix" yaml:"api_prefix"`

	// Cors CORS configuration
	Cors *CorsConfig `json:"cors,omitempty" yaml:"cors,omitempty"`

	// IdleTimeout Idle timeout
	IdleTimeout *time.Duration `json:"idle_timeout,omitempty" yaml:"idle_timeout,omitempty"`

	// ListenAddress Address to listen on
	ListenAddress string `json:"listen_address" yaml:"listen_address"`

	// ReadHeaderTimeout HTTP headers receive timeout
	ReadHeaderTimeout *time.Duration `json:"read_header_timeout,omitempty" yaml:"read_header_timeout,omitempty"`

	// ReadTimeout HTTP read timeout
	ReadTimeout *time.Duration `json:"read_timeout,omitempty" yaml:"read_timeout,omitempty"`

	// Telemetry Telemetry configuration
	Telemetry *TelemetryConfig `json:"telemetry,omitempty" yaml:"telemetry,omitempty"`

	// TLS TLS configuration
	TLS *TLSConfig `json:"tls,omitempty" yaml:"tls,omitempty"`

	// WriteTimeout HTTP write timeout
	WriteTimeout *time.Duration `json:"write_timeout,omitempty" yaml:"write_timeout,omitempty"`
}

// TelemetryConfig Telemetry configuration
type TelemetryConfig struct {
	// Enabled Whether the metrics instrumentation should be enabled
	Enabled bool `json:"enabled" yaml:"enabled"`

	// Path HTTP context where metrics should be exposed
	Path string `json:"path" yaml:"path"`
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"nFXBbtswDP0VgdvRSQNsp9yK7rACLRqsAXYYhkCxaZurLHkUnTgo8u+DbKdO42TecrPFx0fykZReIXZF",
	"6Sxa8TB/BR/nWOjmc/nwfOdsSln40UlCQs5qs2BXIguhh3mqjccIEvQxUxnsMA9+Km4cK9bNWQTlkdMr",
	"xMiySslg+HnvvNCSK3EqWNWWJFcBTCnFWlCtK5sYhAhkVyLMwQuTzWAfwQvu/pmxZNoEthfcDan2ETD+",
	"rogxgfmPo1SPYvx883LrXxhLSCB27K+S6+7p25he2hi3xWTlmDKyfljjbQt4au2BTdgZrzbaVKhcqm7j",
	"GL2f3LWGSYOftHCVo06QpxABCRYN+0De7kAz6134L3S90tkZtR91fZvheAaPup4EYB+8C0FWMEMeNOJU",
	"gz6Hc93wyBvkvh/vk3xurGOil7QqGVOqz+i9uFed7XSAIqgnmZtYXWALXLS4bkQC10fGFObw4aZfvZtu",
	"726OxmgfASUGV0IFukqGWdwnBtXBeiGP7jCgpl8Ope4jMOQF7UonCaM/N1GtISxOC1WNRIPBYNTJqm3i",
	"5US/LpeLrtNeMcZIm6sTbwL+PVKAXEsvaLBA4d1Yo96AfbfEjLa3v1Pfz8ny4TkwbJkER6prMNeVd7pS",
	"/YQPBuLcUp2W/J/PwsF7ZO/Q6rUJCZ5W/z1HyZGV5KgCEcVekfXCVYFWGjLlc1eZRK1RHWje6lg7Z1A3",
	"TS615BfUDRcX1qK2OXIf5oi2Lp0/pr3wbvThm2BDOYMD2dQ11y1JeLnO3kuqHR2IYIPs20xn09n0cyjE",
	"lWh1STCHT9PZdNZFCzLu938CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
