// Package config provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package config

import (
	"time"
)

// TLSConfig TLS configuration
type TLSConfig struct {
	// CertFile Path to file with certificate bundle
	CertFile string `json:"cert_file" yaml:"cert_file"`

	// KeyFile Path to file with private key
	KeyFile string `json:"key_file" yaml:"key_file"`
}

// CorsConfig CORS configuration
type CorsConfig struct {
	// AllowedOrigins AllowedOrigins controls value of Access-Control-Allow-Origin header.
	AllowedOrigins []string `json:"allowed_origins" yaml:"allowed_origins"`

	// MaxAge MaxAge controls value of Access-Control-Max-Age header.
	MaxAge int `json:"max_age" yaml:"max_age"`
}

// ServerConfig Server configuration
type ServerConfig struct {
	// APIPrefix API prefix
	APIPrefix string `json:"api_prefix" yaml:"api_prefix"`

	// Cors CORS configuration
	Cors *CorsConfig `json:"cors,omitempty" yaml:"cors,omitempty"`

	// IdleTimeout Idle timeout
	IdleTimeout *time.Duration `json:"idle_timeout,omitempty" yaml:"idle_timeout,omitempty"`

	// ListenAddress Address to listen on
	ListenAddress string `json:"listen_address" yaml:"listen_address"`

	// ReadHeaderTimeout HTTP headers receive timeout
	ReadHeaderTimeout *time.Duration `json:"read_header_timeout,omitempty" yaml:"read_header_timeout,omitempty"`

	// ReadTimeout HTTP read timeout
	ReadTimeout *time.Duration `json:"read_timeout,omitempty" yaml:"read_timeout,omitempty"`

	// Telemetry Telemetry configuration
	Telemetry *TelemetryConfig `json:"telemetry,omitempty" yaml:"telemetry,omitempty"`

	// TLS TLS configuration
	TLS *TLSConfig `json:"tls,omitempty" yaml:"tls,omitempty"`

	// WriteTimeout HTTP write timeout
	WriteTimeout *time.Duration `json:"write_timeout,omitempty" yaml:"write_timeout,omitempty"`
}

// TelemetryConfig Telemetry configuration
type TelemetryConfig struct {
	// Enabled Whether the metrics instrumentation should be enabled
	Enabled bool `json:"enabled" yaml:"enabled"`

	// Path HTTP context where metrics should be exposed
	Path string `json:"path" yaml:"path"`
}
