// Package config provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package config

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// TLSConfig TLS configuration
type TLSConfig struct {
	// CertFile Path to file with certificate bundle
	CertFile string `json:"cert_file" yaml:"cert_file"`

	// KeyFile Path to file with private key
	KeyFile string `json:"key_file" yaml:"key_file"`
}

// CorsConfig CORS configuration
type CorsConfig struct {
	// AllowedOrigins AllowedOrigins controls value of Access-Control-Allow-Origin header.
	AllowedOrigins []string `json:"allowed_origins" yaml:"allowed_origins"`

	// MaxAge MaxAge controls value of Access-Control-Max-Age header.
	MaxAge int `json:"max_age" yaml:"max_age"`
}

// ServerConfig Server configuration
type ServerConfig struct {
	// APIPrefix API prefix
	APIPrefix string `json:"api_prefix" yaml:"api_prefix"`

	// Cors CORS configuration
	Cors *CorsConfig `json:"cors,omitempty" yaml:"cors,omitempty"`

	// IdleTimeout Idle timeout
	IdleTimeout *time.Duration `json:"idle_timeout,omitempty" yaml:"idle_timeout,omitempty"`

	// ListenAddress Address to listen on
	ListenAddress string `json:"listen_address" yaml:"listen_address"`

	// ReadHeaderTimeout HTTP headers receive timeout
	ReadHeaderTimeout *time.Duration `json:"read_header_timeout,omitempty" yaml:"read_header_timeout,omitempty"`

	// ReadTimeout HTTP read timeout
	ReadTimeout *time.Duration `json:"read_timeout,omitempty" yaml:"read_timeout,omitempty"`

	// Telemetry Telemetry configuration
	Telemetry *TelemetryConfig `json:"telemetry,omitempty" yaml:"telemetry,omitempty"`

	// TLS TLS configuration
	TLS *TLSConfig `json:"tls,omitempty" yaml:"tls,omitempty"`

	// WriteTimeout HTTP write timeout
	WriteTimeout *time.Duration `json:"write_timeout,omitempty" yaml:"write_timeout,omitempty"`
}

// TelemetryConfig Telemetry configuration
type TelemetryConfig struct {
	// Enabled Whether the metrics instrumentation should be enabled
	Enabled bool `json:"enabled" yaml:"enabled"`

	// Path HTTP context where metrics should be exposed
	Path string `json:"path" yaml:"path"`
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"nFXBbtswDP0VgdvRSQP0llvRHVagRYM1wA7DECg2bXOVJY+iEwdF/n2Q7dRpnMxbbrb4+Eg+ktIbxK4o",
	"nUUrHuZv4OMcC918Lh9f7p1NKQs/OklIyFltFuxKZCH0ME+18RhBgj5mKoMd5sFPxY1jxbo5i6A8cnqD",
	"GFlWKRkMPx+dF1pyJU4Fq9qS5CqAKaVYC6p1ZRODEIHsSoQ5eGGyGewjeMXdPzOWTJvA9oq7IdU+Asbf",
	"FTEmMP9xlOpRjJ/vXm79C2MJCcSO/VVy3T9/G9NLG+O2mKwcU0bWD2u8awHPrT2wCTvj1UabCpVL1V0c",
	"o/eT+9YwafCTFq5y1AnyFCIgwaJhH8jbHWhmvQv/ha5XOjuj9pOu7zIcz+BJ15MA7IN3IcgKZsiDRpxq",
	"0OdwrhseeYPc9+Njki+NdUz0klYlY0r1Gb0XD6qznQ5QBPUkcxOrC2yBixbXjUjg+syYwhw+3fSrd9Pt",
	"3c3RGO0joMTgSqhAV8kwi4fEoDpYL+TRHQbU9Muh1H0EhrygXekkYfTnJqo1hMVpoaqRaDAYjDpZtU28",
	"nOjX5XLRddorxhhpc3XiTcC/RwqQa+kFDRYovBtr1Duw75aY0fb2d+rHOVk+vgSGLZPgSHUN5rryTleq",
	"n/DBQJxbqtOS//NZOHiP7B1avTYhwdPqv+coObKSHFUgotgrsl64KtBKQ6Z87iqTqDWqA817HWvnDOqm",
	"yaWW/IK64eLCWtQ2R+7DHNHWpfPHtBfejT58E2woZ3Agm7rmuiUJL9fZe0m1owMRbJB9m+lsOpvehkJc",
	"iVaXBHO4nc6msy5akHG//xMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
