// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

// SystemVersionInfo Encapsulates common version information
type SystemVersionInfo struct {
	// BuildTime Time when application was built
	BuildTime *string `json:"build-time,omitempty" yaml:"build-time,omitempty"`

	// BuildUser User who built application
	BuildUser *string `json:"build-user,omitempty" yaml:"build-user,omitempty"`

	// Revision VCS revision
	Revision *string `json:"revision,omitempty" yaml:"revision,omitempty"`

	// Version Application version
	Version *string `json:"version,omitempty" yaml:"version,omitempty"`
}
